[workspace]
resolver = "3"
members = ["language-server","interpreter"]
exclude = ["zed-extension", "tree-sitter-moss"]

[workspace.dependencies]
log = "0.4.28"
tokio = { version = "1.48.0" }
hashbrown = { version = "0.16.1", features = ["default-hasher"] }
